# Generated by Django 4.1 on 2022-08-05 08:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 5, 8, 21, 9, 592351, tzinfo=datetime.timezone.utc)),
        ),
    ]
